import re
from html.parser import HTMLParser

VOID_ELEMENTS = {
    "area", "base", "br", "col", "embed", "hr", "img", "input",
    "link", "meta", "param", "source", "track", "wbr",
}
# Elements dropped entirely (including their content) - no legitimate use in a
# self-contained generated page, and each is a known vector for pulling in
# untrusted remote content or hijacking navigation.
DROPPED_ELEMENTS = {"iframe", "object", "applet", "base", "embed"}
DANGEROUS_URI_PREFIXES = ("javascript:", "data:text/html", "vbscript:")

_FENCE_PATTERN = re.compile(r"^```(?:html)?\s*|\s*```$", re.IGNORECASE)
_STRIPPABLE_URL_CHARS = re.compile(r"[\t\n\r]")

WATERMARK_FOOTER = (
    '<div style="position:fixed;bottom:12px;right:12px;background:#111;color:#fff;'
    'padding:6px 12px;border-radius:6px;font-size:12px;font-family:sans-serif;'
    'z-index:9999;opacity:0.85;">'
    '\n  Built with <a href="https://www.webneststudio.co.in" target="_blank" '
    'rel="noopener noreferrer" style="color:#f5c542;text-decoration:none;">WebNest Studio</a>'
    "\n</div>"
)
TRACKING_COMMENT = "<!-- Generated by WebNest Studio AI Page Builder - webneststudio.co.in -->"


class MalformedOutputError(Exception):
    """Raised when the model's output cannot be reduced to a valid HTML document."""


def extract_html_document(raw: str) -> str:
    """Strips markdown fences / stray commentary and isolates the HTML document
    the model returned. Raises MalformedOutputError if no <!DOCTYPE html> is found."""
    text = _FENCE_PATTERN.sub("", raw.strip()).strip()

    lower = text.lower()
    start = lower.find("<!doctype html")
    if start == -1:
        raise MalformedOutputError("Model output did not contain a valid HTML document")
    text = text[start:]

    lower = text.lower()
    end = lower.rfind("</html>")
    if end == -1:
        # No closing </html> means the model's output was cut off (almost always
        # a maxOutputTokens truncation) before finishing the document - critically,
        # this also means any <style>/<script> block opened earlier is left
        # unterminated. html.parser silently discards everything after an
        # unterminated CDATA element on close() rather than erroring, so if this
        # weren't caught here, sanitize_html() would quietly drop the entire rest
        # of the page and return a mostly-empty "successful" document instead of
        # failing loudly.
        raise MalformedOutputError("Model output was truncated before the document was complete")
    text = text[: end + len("</html>")]

    return text.strip()


class _Sanitizer(HTMLParser):
    """Rebuilds the document while dropping elements/attributes that have no
    place in a self-contained static page and are common XSS/exfiltration
    vectors: remote iframes/objects/embeds, external <script src>, inline
    event handler attributes, javascript: URIs, meta-refresh redirects, and
    form actions (a generated page has no backend to submit to)."""

    def __init__(self) -> None:
        super().__init__(convert_charrefs=False)
        self._out: list[str] = []
        self._skip_tag: str | None = None
        self._skip_depth = 0

    def handle_decl(self, decl: str) -> None:
        self._out.append(f"<!{decl}>")

    def handle_comment(self, data: str) -> None:
        self._out.append(f"<!--{data}-->")

    def handle_data(self, data: str) -> None:
        if self._skip_tag is None:
            self._out.append(data)

    def handle_entityref(self, name: str) -> None:
        if self._skip_tag is None:
            self._out.append(f"&{name};")

    def handle_charref(self, name: str) -> None:
        if self._skip_tag is None:
            self._out.append(f"&#{name};")

    def handle_startendtag(self, tag: str, attrs) -> None:
        self._emit_start(tag, attrs, self_closing=True)

    def handle_starttag(self, tag: str, attrs) -> None:
        self._emit_start(tag, attrs, self_closing=False)

    def handle_endtag(self, tag: str) -> None:
        tag_lower = tag.lower()
        if self._skip_tag is not None:
            if tag_lower == self._skip_tag:
                self._skip_depth -= 1
                if self._skip_depth == 0:
                    self._skip_tag = None
            return
        if tag_lower not in VOID_ELEMENTS:
            self._out.append(f"</{tag}>")

    def _emit_start(self, tag: str, attrs, self_closing: bool) -> None:
        tag_lower = tag.lower()

        if self._skip_tag is not None:
            if tag_lower == self._skip_tag and not self_closing:
                self._skip_depth += 1
            return

        attrs_dict = {name.lower(): value for name, value in attrs}

        if tag_lower in DROPPED_ELEMENTS:
            if not self_closing:
                self._skip_tag = tag_lower
                self._skip_depth = 1
            return

        if tag_lower == "meta" and (attrs_dict.get("http-equiv") or "").lower() == "refresh":
            return

        if tag_lower == "script" and attrs_dict.get("src"):
            if not self_closing:
                self._skip_tag = "script"
                self._skip_depth = 1
            return

        if tag_lower == "form":
            attrs_dict.pop("action", None)

        cleaned: dict[str, str | None] = {}
        for name, value in attrs_dict.items():
            if name.startswith("on"):
                continue
            if name in ("href", "src") and value:
                # Browsers strip ASCII tab/newline/CR from URLs anywhere before
                # resolving the scheme (WHATWG URL spec), so "jav\tascript:" is
                # still executed as javascript: - strip the same characters
                # here before the prefix check, not just at the ends.
                normalized = _STRIPPABLE_URL_CHARS.sub("", value).strip().lower()
                if any(normalized.startswith(prefix) for prefix in DANGEROUS_URI_PREFIXES):
                    continue
            cleaned[name] = value

        attr_str = "".join(_render_attr(name, value) for name, value in cleaned.items())
        self._out.append(f"<{tag}{attr_str}{' />' if self_closing else '>'}")

    def get_html(self) -> str:
        return "".join(self._out)


def _render_attr(name: str, value: str | None) -> str:
    if value is None:
        return f" {name}"
    escaped = value.replace("&", "&amp;").replace('"', "&quot;")
    return f' {name}="{escaped}"'


def sanitize_html(html: str) -> str:
    sanitizer = _Sanitizer()
    sanitizer.feed(html)
    sanitizer.close()
    return sanitizer.get_html()


def inject_watermark(html: str) -> str:
    result = html
    lower = result.lower()

    if lower.startswith("<!doctype html"):
        doctype_end = result.find(">")
        if doctype_end != -1:
            insert_at = doctype_end + 1
            result = f"{result[:insert_at]}\n{TRACKING_COMMENT}{result[insert_at:]}"

    lower = result.lower()
    body_close = lower.rfind("</body>")
    if body_close != -1:
        result = f"{result[:body_close]}{WATERMARK_FOOTER}\n{result[body_close:]}"
    else:
        result = f"{result}\n{WATERMARK_FOOTER}"

    return result


def finalize_generated_html(raw: str) -> str:
    """Full post-processing pipeline: extract -> sanitize -> watermark.
    Raises MalformedOutputError if the model output isn't a usable HTML document."""
    document = extract_html_document(raw)
    sanitized = sanitize_html(document)
    return inject_watermark(sanitized)
